# Generated by Django 5.2.5 on 2025-08-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('ACADEMIC', 'Académique'), ('SPORT', 'Sportif'), ('CULTURAL', 'Culturel'), ('EXTERNAL', 'Externe')], default='ACADEMIC', max_length=20),
        ),
    ]
