# Generated by Django 5.2.5 on 2025-08-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='professeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='salle',
            field=models.CharField(blank=True, choices=[('Salle A', 'Salle A'), ('Salle B', 'Salle B'), ('Salle C', 'Salle C'), ('Salle D', 'Salle D')], max_length=20, null=True),
        ),
    ]
