# Generated by Django 5.2.5 on 2025-09-29 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_convert_data'),
        ('schedule', '0003_annee_cours_filiere_salle_alter_schedule_options_and_more'),
    ]

    operations = [
    ]
