# Generated by Django 5.2.5 on 2025-09-29 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_merge_20250929_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='annee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.annee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='cours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.cours'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='filiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.filiere'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='salle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedule.salle'),
            preserve_default=False,
        ),
    ]
